---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# lglasso

<!-- badges: start -->
<!-- badges: end -->

<div style="text-align: justify"> 

The initial version of the package implemented the algorithms proposed in Zhou et al. (2024),  which aims to estimate the high-dimensional networks  from longitudinal data using Gassian grapical models. Though the overarching goal of the package is the same as previous version, i.e., explore the possible correlations between high-dimensional data to  improve the estimations of networks. this updated version does add several extensions, which include

(1) Heterogeneous networks. The models in previous version (i.e., in the 2024 paper) assumed a stationary process for the longitudinal data. This might not be the case in many situations, e.g, the antibodies network before and after vaccination,  metabolites network before and after the initialization of the treatment for cancer patients. Also, the metabolites in different tissues e.g.,  colon vs blood vs ileum,  can also interact with each other in different way. In this version of \code{lglasso}, the function \code{lglasso} are extended to accommodate s such important scenarios.   


(2) This version lglasso provide function  \code{CVlglasso} to facilitate the selection of tuning parameter.  


</div>
## Installation

You can install the development version of lglasso from [GitHub](https://github.com/) with:

First, install the package remotes:

```
install.packages("remotes")
```

Then install lglasso :

```
remotes::install_github("jiezhou-2/lglasso", ref ="main") 
```



## How to use

 Please see [package website](https://jiezhou-2.github.io/lglasso/). 
 


[1] Zhou J, Gui J, Viles WD, Chen H, Li S, Madan JC, Coker MO, Hoen AG. Identifying stationary microbial interaction networks based on irregularly spaced longitudinal 16S rRNA gene sequencing data. Front Microbiomes. 2024;3:1366948. doi: 10.3389/frmbi.2024.1366948. Epub 2024 Jun 2. PMID: 40687607; PMCID: PMC12276884.

[2] Friedman J., Hastie T., Tibshirani R. (2019)  Graphical Lasso: Estimation of Gaussian Graphical Models, Version: 1.11. https://CRAN.R-project.org/package=glasso. 
