---
title: "Case study: antibody interaction networks"
author: "Jie Zhou"
date: "2025-07-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(matrixcalc)
library(RCy3)
library(igraph)
library(fake)
library(tidyr)
library(devtools)
load_all()
load("/Users/f003r0s/Desktop/Anne_lab_projects/lglassoProject/data/b_set.Rdata")
#load("/Users/f003r0s/Desktop/Anne_lab_projects/lglassoProject/data/a_set.Rdata")
variables=c("subject_accession","visit_name","feature","value_reported","infant_arm","delivery_mode","arm_name")
data=data_extra[,variables]
set.seed(1)
```

## data


```{r}
 wideData=reshape(data=data,idvar =  c("subject_accession","visit_name","infant_arm","delivery_mode","arm_name"),
                  timevar = "feature", direction = "wide")

#wideData=wideData[,-c(3:5)]
timepoints=ifelse(wideData$visit_name=="prevaccinated",2,ifelse(wideData$visit_name=="mo4",4,ifelse(wideData$visit_name=="vaccinated",5,9)))

wideData$visit_name=timepoints
wideData=wideData[order(wideData$subject_accession,wideData$visit_name),]
index=which(is.na(wideData),arr.ind = T)
aa=as.numeric(names(which(table(index[,2])>0.1*nrow(wideData))))
fulldata=wideData[,-aa]
fulldata[78,4]="Vaginal Delivery"
fulldata[is.na(fulldata)]<- 0
fulldata[,-c(1:5)]=log10(1+fulldata[,-c(1:5)])
index=which(fulldata$subject_accession==23)
fulldata=fulldata[-index,]

ddd=c()
for (i in c(2,4,5,9)) {
  index=which(fulldata$visit_name==i)
  dd=fulldata[index,]
  dd[,-c(1:5)]=scale(dd[,-c(1:5)],center = TRUE,scale = FALSE)
  ddd=rbind(ddd,dd)
}
fulldata=ddd[order(ddd$subject_accession,ddd$visit_name),]

```

## homogeneous subjects

###  one-stage model (post vaccination data)

```{r,eval=FALSE,echo=FALSE}
index=which(fulldata$visit_name==2)
postdata=fulldata[-index,]
lambda=exp(seq(-10,-1,length=10))
aa1=CVlglasso(data=postdata[,-c(3:5)],lambda = lambda,K=3,trace = FALSE,random = FALSE)
plot(aa1)
```


```{r,echo=FALSE}
aa1=readRDS("homo1.rds")
index=which.min(aa1$cv_error)
print(aa1$lambda[index])
plot(aa1)
```


### two-stage model (full data)

```{r,eval=FALSE,echo=FALSE}
index=which(is.na(wideData),arr.ind = T)
aa=as.numeric(names(which(table(index[,2])>0.1*nrow(wideData))))
fulldata=wideData[,-aa]
index=which(is.na(fulldata),arr.ind = T)
for (i in 1:nrow(index)) {
  fulldata[index[i,1],index[i,2]]=0
}
fulldata[,-c(1,2)]=log10(1+fulldata[,-c(1,2)])
index=which(fulldata$subject_accession==23)
fulldata=fulldata[-index,]
group=ifelse(fulldata$visit_name==2,1,2)
lambda1=exp(seq(-10,-1,length=5))
lambda2=exp(seq(-3,-1,length=5))
lambda=expand.grid(lambda1,lambda2)
aa1=CVlglasso(data=fulldata,lambda = lambda,K=2,trace = TRUE,random = FALSE,group = group,NN=100)
plot(aa1)
```


## heterogeneous subjects

### one-stage model (post vaccination data)

```{r,eval=FALSE,echo=FALSE}
lambda=exp(seq(-10,-1,length=4))
aa1=CVlglasso(data=postdata[,-c(3:5)],lambda = lambda,K=2,trace = FALSE,random = TRUE,NN=1000)
plot(aa1)
```

```{r,echo=FALSE}
aa2=readRDS("heter1.rds")
index=which.min(aa2$cv_error)
print(aa2$lambda[index])
plot(aa2)
```

### two-stage model (full data)

```{r,eval=FALSE,echo=FALSE}
lambda1=exp(seq(-10,-1,length=2))
lambda2=exp(seq(-5,-1,length=2))
lambda=expand.grid(lambda1,lambda2)
aa1=CVlglasso(data=fulldata[,-c(3:5)],lambda = lambda,K=2,trace = FALSE,random = TRUE,group = group,NN=100)
plot(aa1)
```
```{r,echo=FALSE}
aa2=readRDS("heter2.rds")
plot(aa2)
```
