---
title: "lglasso: identify networks from correlated data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction_of_lglasso_package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

In this vignette, we show how to use **lglasso** package to estimate single-stage or double-stage networks from longitudinal data. 

In  section 1 and 2, we use simulated data to demonstrate how to use the two main function *lglasso()* and *CVlglasso()* respectively. 

In section 3 and 4, we use the real antibody titer data from a large vaccine study  to show that the how the analysis can lead to meaningful biological interpretations. 

The function *Simulate()* for generating the simulated data can be found in file *simulations.R* in folder *scripts* of this repo. You can use it to play around to test the main functions.  Unfortunately, the antibody real data is not publicly available. If you need these data for your research, please contact me at *chowstat@gmail.com* .   

The algorithm is pretty stable, as you can see it converged nicely for both the simulated data and real data. However, based on my experience, the computational speed is not ideal yet. For the real data in which there are 83 features, it takes *lglasso* 2.2 minutes  to converge for single network estimation and 5.7 minutes for double network estimation (  the results are listed in section 3).    But if you think the speed is acceptable for you data, go ahead and give it a try! 

### Simulation

[1. lglasso examples](lglasso.html)

[2. CVlglasso examples](CVlglasso.html)

### Real data

[3.lglasso examples](realDatab.html)

[4.CVlglasso examples](cvRealData.html)






