---
title: "Case study: antibody interaction networks"
author: "Jie Zhou"
date: "2025-07-10"
output: html_document
---

```{r setup, include=FALSE,echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(matrixcalc)
library(RCy3)
library(igraph)
library(fake)
library(tidyr)
library(Matrix)
library(devtools)
library(igraph)
load_all()
load("/Users/f003r0s/Desktop/Anne_lab_projects/lglassoProject/data/b_set.Rdata")
variables=c("subject_accession","visit_name","feature","value_reported","infant_arm","delivery_mode","maternal_arm","gestational_age_vaccination","infant_sex")
data=data_extra[,variables]
set.seed(1)
```

## data


```{r,echo=FALSE}
 wideData=reshape(data=data,idvar =  c("subject_accession","visit_name","infant_arm","delivery_mode","maternal_arm","infant_sex","gestational_age_vaccination"),
                  timevar = "feature", direction = "wide")

#wideData=wideData[,-c(3:5)]
wideData$visit_name=ifelse(wideData$visit_name=="prevaccinated",2,
                  ifelse(wideData$visit_name=="mo4",4,
                         ifelse(wideData$visit_name=="vaccinated",5,
                                9)))

wideData=wideData[order(wideData$subject_accession,wideData$visit_name),]
index=which(is.na(wideData),arr.ind = T)
aa=as.numeric(names(which(table(index[,2])>0.1*nrow(wideData))))
fulldata=wideData[,-aa]
dd=fulldata[,-c(1:7)]
dd[is.na(dd)]<-0
fulldata[,-c(1:7)]=dd
fulldata=fulldata[-78,]
index1=which(fulldata$visit_name==2)
index2=which(fulldata$visit_name!=2)
# abundancePre=data.frame(antibody=substr(colnames(fulldata),                         16,length(colnames(fulldata)))[-c(1:7)],abundance=apply(fulldata[index1,-c(1:5)], 2, mean))
# abundancePost=data.frame(antibody=substr(colnames(fulldata),16,length(colnames(fulldata)))[-c(1:5)],abundance=apply(fulldata[index2,-c(1:7)], 2, mean))
# write.csv(abundancePre,file = "abundancePre.CSV")
# write.csv(abundancePost,file = "abundancePost.CSV")
fulldata[,-c(1:7)]=log10(1+fulldata[,-c(1:7)])
 # index=which(fulldata$subject_accession==23)
 # fulldata=fulldata[-index,]

ddd=c()
for (i in c(2,4,5,9)) {
  index=which(fulldata$visit_name==i)
  dd=fulldata[index,]
  dd[,-c(1:7)]=scale(dd[,-c(1:7)],center = TRUE,scale = FALSE)
  ddd=rbind(ddd,dd)
}
fulldata=ddd[order(ddd$subject_accession,ddd$visit_name),]
antibodyName=substr(colnames(fulldata),16,length(colnames(fulldata)))[-c(1:7)]
colnames(fulldata)[-c(1:7)]=antibodyName
```

```{r}
dim(fulldata)
fulldata[1:5,1:8]
colnames(fulldata)
```


## homogeneous subjects

###  one-stage model (post vaccination data,2.2min)

```{r}
index=which(fulldata$visit_name==2)
postdata=fulldata[-index,]
aa1=lglasso(data=postdata[,-c(3:7)],lambda = 0.004961126,random = FALSE,trace = T,tol = 0.01)
aa1$wi[[1]][1:10,1:10]
aa1$tau

```

```{r,echo=FALSE}
adjMatrix=ifelse(abs(aa1$wi[[1]])<10^(-5),0,1)
gg=graph_from_adjacency_matrix(
adjmatrix =  adjMatrix,
mode = c("undirected"),
weighted = NULL,
diag = FALSE
)
edgeListHomo1=as_edgelist(gg)
write.csv(edgeListHomo1,file="edgeListHomo1.CSV")
saveRDS(edgeListHomo1,file="edgeListHomo1.rds")
```



### two-stage model (full data)

```{r}
group=ifelse(fulldata$visit_name==2,1,2)
aa2=lglasso(data=fulldata[,-c(3:7)],lambda = c(0.005,1),group = group,random = FALSE,trace = T,tol=0.01)
aa2$wi[[1]][1:10,1:10]
aa2$wi[[2]][1:10,1:10]
aa2$tau
```


## heterogeneous subjects

### one-stage model (post vaccination data,2.2min)

```{r, warning=FALSE,message=FALSE}
aa1=lglasso(data=postdata[,-c(3:7)],lambda = 0.005670864,random = TRUE,trace = T)
aa1$wi[[1]][1:10,1:10]
aa1$tau[1:10]
aa1$alpha
```

```{r}
dd=unique(postdata[,c(1,3:7)])
summary(lm(aa1$tau~infant_arm+delivery_mode+maternal_arm+infant_sex+gestational_age_vaccination,data=dd))

```

```{r,echo=FALSE}
adjMatrix=ifelse(abs(aa1$wi[[1]])<10^(-5),0,1)
gg=graph_from_adjacency_matrix(
adjmatrix =  adjMatrix,
mode = c("undirected"),
weighted = NULL,
diag = FALSE
)
edgeListHeter1=as_edgelist(gg)
write.csv(edgeListHeter1,file="edgeListHeter1.CSV")
saveRDS(edgeListHeter1,file="edgeListHeter1.rds")
```



### two-stage model (full data,5.7min)

```{r}
group=ifelse(fulldata$visit_name==2,1,2)
aa2=lglasso(data=fulldata[,-c(3:7)],lambda = c(0.01174363,0.329193),group = group,random = TRUE,trace = T,tol = 0.01)
aa2$wi[[1]][1:10,1:10]
aa2$wi[[2]][1:10,1:10]
```

```{r}
dd=unique(fulldata[,c(1,3:7)])
summary(lm(aa2$tau~infant_arm+delivery_mode+maternal_arm+infant_sex+gestational_age_vaccination,data=dd))
```


```{r,echo=FALSE}
adjMatrix1=ifelse(abs(aa2$wi[[1]])<10^(-5),0,1)
adjMatrix2=ifelse(abs(aa2$wi[[2]])<10^(-5),0,1)
write.csv(adjMatrix1,file = "adjMatrixPre.CSV")
write.csv(adjMatrix2,file = "adjMatrixPost.CSV")
gg1=graph_from_adjacency_matrix(
adjmatrix =  adjMatrix1,
mode = c("undirected"),
weighted = NULL,
diag = FALSE
)

gg2=graph_from_adjacency_matrix(
adjmatrix =  adjMatrix2,
mode = c("undirected"),
weighted = NULL,
diag = FALSE
)
edgeListHeter21=as_edgelist(gg1)
edgeListHeter22=as_edgelist(gg2)
edgeListHeter2=list(edgeListHeter21,edgeListHeter22)
write.csv(edgeListHeter21,file="edgeListHeter21.CSV")
write.csv(edgeListHeter22,file="edgeListHeter22.CSV")
saveRDS(edgeListHeter2,file="edgeListHeter2.rds")
```
