// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// phifunction
arma::mat phifunction(const arma::vec& t, double tau, double expFix);
RcppExport SEXP _lglasso_phifunction(SEXP tSEXP, SEXP tauSEXP, SEXP expFixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type expFix(expFixSEXP);
    rcpp_result_gen = Rcpp::wrap(phifunction(t, tau, expFix));
    return rcpp_result_gen;
END_RCPP
}
// conDensityTau
double conDensityTau(double tau, SEXP datai, Rcpp::List wi, double alpha, SEXP groupi, double expFix);
RcppExport SEXP _lglasso_conDensityTau(SEXP tauSEXP, SEXP dataiSEXP, SEXP wiSEXP, SEXP alphaSEXP, SEXP groupiSEXP, SEXP expFixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< SEXP >::type datai(dataiSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type wi(wiSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type groupi(groupiSEXP);
    Rcpp::traits::input_parameter< double >::type expFix(expFixSEXP);
    rcpp_result_gen = Rcpp::wrap(conDensityTau(tau, datai, wi, alpha, groupi, expFix));
    return rcpp_result_gen;
END_RCPP
}
// importanceSample
Rcpp::DataFrame importanceSample(int n, SEXP datai, Rcpp::List wi, double alpha, SEXP groupi, double expFix);
RcppExport SEXP _lglasso_importanceSample(SEXP nSEXP, SEXP dataiSEXP, SEXP wiSEXP, SEXP alphaSEXP, SEXP groupiSEXP, SEXP expFixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< SEXP >::type datai(dataiSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type wi(wiSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type groupi(groupiSEXP);
    Rcpp::traits::input_parameter< double >::type expFix(expFixSEXP);
    rcpp_result_gen = Rcpp::wrap(importanceSample(n, datai, wi, alpha, groupi, expFix));
    return rcpp_result_gen;
END_RCPP
}
// importanceEstimates
Rcpp::List importanceEstimates(SEXP importancesSample, SEXP datai, SEXP groupi, double expFix);
RcppExport SEXP _lglasso_importanceEstimates(SEXP importancesSampleSEXP, SEXP dataiSEXP, SEXP groupiSEXP, SEXP expFixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type importancesSample(importancesSampleSEXP);
    Rcpp::traits::input_parameter< SEXP >::type datai(dataiSEXP);
    Rcpp::traits::input_parameter< SEXP >::type groupi(groupiSEXP);
    Rcpp::traits::input_parameter< double >::type expFix(expFixSEXP);
    rcpp_result_gen = Rcpp::wrap(importanceEstimates(importancesSample, datai, groupi, expFix));
    return rcpp_result_gen;
END_RCPP
}
// AA
Rcpp::List AA(SEXP B, SEXP data, double expFix, int maxit, double tol, Rcpp::NumericVector lower, Rcpp::NumericVector upper);
RcppExport SEXP _lglasso_AA(SEXP BSEXP, SEXP dataSEXP, SEXP expFixSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type B(BSEXP);
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type expFix(expFixSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(AA(B, data, expFix, maxit, tol, lower, upper));
    return rcpp_result_gen;
END_RCPP
}
// AAheter
Rcpp::List AAheter(SEXP data, Rcpp::List wi, double alpha, SEXP group, int l, double expFix);
RcppExport SEXP _lglasso_AAheter(SEXP dataSEXP, SEXP wiSEXP, SEXP alphaSEXP, SEXP groupSEXP, SEXP lSEXP, SEXP expFixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type wi(wiSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type l(lSEXP);
    Rcpp::traits::input_parameter< double >::type expFix(expFixSEXP);
    rcpp_result_gen = Rcpp::wrap(AAheter(data, wi, alpha, group, l, expFix));
    return rcpp_result_gen;
END_RCPP
}
// simulate_randomTau
Rcpp::List simulate_randomTau(int n, int p, int m1, int tt, int m2, double alpha, int group);
RcppExport SEXP _lglasso_simulate_randomTau(SEXP nSEXP, SEXP pSEXP, SEXP m1SEXP, SEXP ttSEXP, SEXP m2SEXP, SEXP alphaSEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< int >::type tt(ttSEXP);
    Rcpp::traits::input_parameter< int >::type m2(m2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_randomTau(n, p, m1, tt, m2, alpha, group));
    return rcpp_result_gen;
END_RCPP
}
// simulate_long
Rcpp::List simulate_long(int n, int p, int m1, Rcpp::NumericVector tau, int tt, int m2);
RcppExport SEXP _lglasso_simulate_long(SEXP nSEXP, SEXP pSEXP, SEXP m1SEXP, SEXP tauSEXP, SEXP ttSEXP, SEXP m2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< int >::type tt(ttSEXP);
    Rcpp::traits::input_parameter< int >::type m2(m2SEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_long(n, p, m1, tau, tt, m2));
    return rcpp_result_gen;
END_RCPP
}
// BB
Rcpp::List BB(SEXP A, SEXP data, Rcpp::NumericVector lambda, bool random, Rcpp::Nullable<Rcpp::NumericVector> tau, double rho, int maxit, double eps_abs, double eps_rel);
RcppExport SEXP _lglasso_BB(SEXP ASEXP, SEXP dataSEXP, SEXP lambdaSEXP, SEXP randomSEXP, SEXP tauSEXP, SEXP rhoSEXP, SEXP maxitSEXP, SEXP eps_absSEXP, SEXP eps_relSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type A(ASEXP);
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type random(randomSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type eps_abs(eps_absSEXP);
    Rcpp::traits::input_parameter< double >::type eps_rel(eps_relSEXP);
    rcpp_result_gen = Rcpp::wrap(BB(A, data, lambda, random, tau, rho, maxit, eps_abs, eps_rel));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lglasso_phifunction", (DL_FUNC) &_lglasso_phifunction, 3},
    {"_lglasso_conDensityTau", (DL_FUNC) &_lglasso_conDensityTau, 6},
    {"_lglasso_importanceSample", (DL_FUNC) &_lglasso_importanceSample, 6},
    {"_lglasso_importanceEstimates", (DL_FUNC) &_lglasso_importanceEstimates, 4},
    {"_lglasso_AA", (DL_FUNC) &_lglasso_AA, 7},
    {"_lglasso_AAheter", (DL_FUNC) &_lglasso_AAheter, 6},
    {"_lglasso_simulate_randomTau", (DL_FUNC) &_lglasso_simulate_randomTau, 7},
    {"_lglasso_simulate_long", (DL_FUNC) &_lglasso_simulate_long, 6},
    {"_lglasso_BB", (DL_FUNC) &_lglasso_BB, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_lglasso(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
