# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_lglasso_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_lglasso_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_lglasso_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_lglasso_rcpparma_bothproducts`, x)
}

phifunction <- function(t, tau, ty) {
    .Call(`_lglasso_phifunction`, t, tau, ty)
}

iss <- function(idata, itau, ty) {
    .Call(`_lglasso_iss`, idata, itau, ty)
}

