# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lglasso_cpp_obj <- function(X, t, B, tau) {
    .Call('_lglasso_lglasso_cpp_obj', PACKAGE = 'lglasso', X, t, B, tau)
}

