# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Exponential correlation matrix
#'
#' Computes \eqn{M_{ij} = \exp(-\tau |t_i - t_j|^{expFix})} with ones on the diagonal.
#'
#' @param t Numeric vector of time points.
#' @param tau Positive scalar decay parameter.
#' @param expFix Exponent applied to the distance (default 1).
#' @return An n x n numeric matrix.
#' @examples
#' phifunction(1:5, tau = 0.3)
#' phifunction(c(0, 2, 5), tau = 0.7, expFix = 2)
#' @export
phifunction <- function(t, tau, expFix = 1.0) {
    .Call(`_lglasso_phifunction`, t, tau, expFix)
}

#' density function in EM algorithm
#'
#' Computes conditional likelihood for heterogeneous models
#'
#' @param tau the dampening rate
#' @param datai the data set for subject i (col 1 = id, col 2 = time, rest = variables)
#' @param wi named list of precision matrices, names matching the values of groupi
#' @param alpha the rate in exponential distribution
#' @param groupi the data point indices (group labels), one per row of datai
#' @param expFix a scalar specifying the form of the correlation function
#' @noRd
#' @returns a numeric standing for the likelihood for a given subject
conDensityTau <- function(tau, datai, wi, alpha, groupi, expFix = 1.0) {
    .Call(`_lglasso_conDensityTau`, tau, datai, wi, alpha, groupi, expFix)
}

#' Function for generating the samples from posterior distribution in EM algorithm
#'
#' @param n the number of random samples
#' @param datai the data for subject i
#' @param wi the given precision matrix (named list, names = group labels)
#' @param alpha the exponential distribution with rate alpha
#' @param groupi specify how datai is grouped
#' @param expFix a scalar specifying the form of the correlation function
#' @noRd
#' @returns a data frame for samples and their weights
importanceSample <- function(n, datai, wi, alpha, groupi, expFix = 1.0) {
    .Call(`_lglasso_importanceSample`, n, datai, wi, alpha, groupi, expFix)
}

#' Function for computing estimates in EM algorithm
#'
#' @param importancesSample the random samples (output of importanceSample: columns sample, weight)
#' @param datai the data for subject i (col 1 = id, col 2 = time, ...)
#' @param groupi specify how datai is grouped
#' @param expFix a scalar specifying the form of the correlation function
#' @noRd
#' @returns a list with estimateTau and a named list estimatePhi
importanceEstimates <- function(importancesSample, datai, groupi, expFix = 1.0) {
    .Call(`_lglasso_importanceEstimates`, importancesSample, datai, groupi, expFix)
}

#' Find the tau's for homogeneous model
#' @param B a list of length 1 or 2 (or a single matrix). Each entry is a p by p
#'   precision matrix; with length 2 they represent the pre- and post-treatment network.
#' @param data a data frame (columns: id, time, p variables) or a list of such data frames
#' @param expFix the parameter in the correlation function
#' @param maxit currently unused (optim defaults are used, as in the R version)
#' @param tol currently unused (optim defaults are used, as in the R version)
#' @param lower lower bound(s) for tau; element k is used for data set k (recycled)
#' @param upper upper bound(s) for tau; element k is used for data set k (recycled)
#' @noRd
#' @returns a list with corMatrix (list of named lists of matrices) and tau
AA <- function(B, data, expFix = 1.0, maxit = 50L, tol = 1e-4, lower = as.numeric( c(0.01, 0.1)), upper = as.numeric( c(10.0, 5.0))) {
    .Call(`_lglasso_AA`, B, data, expFix, maxit, tol, lower, upper)
}

#' Estimate the phimatrix in heterogeneous model
#'
#' @param data longitudinal data set (col 1 = subject id, col 2 = time, rest = variables)
#' @param wi named list of precision matrices (names = group labels)
#' @param alpha exponential distribution with rate alpha
#' @param group specify how data is grouped (one label per row of data)
#' @param l number of random samples in importance sampling
#' @param expFix a scalar specifying the form of the correlation function
#' @noRd
#' @returns a list with Tau (subjects x 1 matrix) and AA (per group, per subject correlation matrices)
AAheter <- function(data, wi, alpha, group, l = 5000L, expFix = 1.0) {
    .Call(`_lglasso_AAheter`, data, wi, alpha, group, l, expFix)
}

#' Simulate data with random tau
#' @param n the number of subjects
#' @param p the dimension of the normal distribution
#' @param m1 the number of edges
#' @param tt the average length of data for each subject
#' @param m2 the number of differences between two networks
#' @param alpha the parameter in the exponential distribution
#' @param group 1 = pre only, otherwise pre and post
#' @noRd
#' @returns a list with data, network, tau and alpha
simulate_randomTau <- function(n, p, m1, tt, m2, alpha, group) {
    .Call(`_lglasso_simulate_randomTau`, n, p, m1, tt, m2, alpha, group)
}

#' Simulate longitudinal data with fixed tau
#'
#' @param n the number of subjects
#' @param p the dimension of the normal distribution
#' @param m1 the number of edges
#' @param tau the dampening rate: length 1 (pre only) or 2 (pre and post)
#' @param tt the maximum number of time points per subject
#' @param m2 the number of differences between the two networks
#' @noRd
#' @returns a list with data, network and tau
simulate_long <- function(n, p, m1, tau, tt = 5L, m2 = 0L) {
    .Call(`_lglasso_simulate_long`, n, p, m1, tau, tt, m2)
}

#' Estimate the precision matrices (ADMM)
#'
#' @param A a list of length 1 or 2 (stages). Each entry is a list of the phi
#'   matrices of all subjects in that stage.
#' @param data a list of data frames (col 1 = id, col 2 = time, rest = variables)
#' @param lambda tuning parameter(s): lambda(1) sparsity, lambda(2) fusion (m = 2)
#' @param random logical, type of the model
#' @param tau needed if random = TRUE (enters the likelihood via log(mean(tau)))
#' @param rho initial ADMM step size (adapted automatically)
#' @param maxit maximum number of ADMM iterations
#' @param eps_abs absolute ADMM tolerance
#' @param eps_rel relative ADMM tolerance
#' @noRd
#' @returns a list with wi (precision matrices), w (covariance matrices) and ll
BB <- function(A, data, lambda, random = FALSE, tau = NULL, rho = 1.0, maxit = 10000L, eps_abs = 1e-6, eps_rel = 1e-5) {
    .Call(`_lglasso_BB`, A, data, lambda, random, tau, rho, maxit, eps_abs, eps_rel)
}

